### ISSUE TITLE
Missing assignment for January 25th!

### ISSUE THREAD

**Issue by natenolting** [fuseZED/Ecommerce#2]
I'm missing your "Bio page" assignment from January 25th. See https://github.com/natenolting/BUAD-3283-E-Commerce-Web-Development/blob/spring2018/course_assignment/course_assignment_06_January_25.md

If you are stuck please ask.

**Comment by swolo** [comment]
Forgot to upload the assignment to cloud storage, couldnt push it to git until I was back in the lab.

**Comment by natenolting** [comment]
Did you upload it to your hosting? I don't see it on http://ecomm.fusezed.com/

**Comment by swolo** [comment]
I had forgotten to edit the index to provide a link to it.

It should be listed at ecomm.fusezed.com now.

Sorry about that.

**Comment by natenolting** [comment]
Looks good!
